#!/bin/bash
# \xe2\x80\x89 is the utf8 representation of \u2009
df=$(
    df -H --output=avail "$BLOCK_INSTANCE" \
        | tail -n1 \
        | sed 's/\s\+\([0-9.]\+\)\(\w\)\s*/\1\xe2\x80\x89\2B/'
)

printf '%s' "$df"