#!/bin/bash

if [[ "$BLOCK_BUTTON" == 4 ]]; then
    change='+5'
elif [[ "$BLOCK_BUTTON" == 5 ]]; then
    change='-5'
fi

vol=$(~/.local/bin/scripts/quodlibet-volume "$change")
if [[ "$?" == 0 ]]; then
    if [[ "$BLOCK_BUTTON" == 1 ]]; then
        ~/.local/bin/scripts/quodlibet-control play-pause
    fi

    printf "%s\u2009%%\n" "$vol"
fi
