#!/bin/bash

if [[ "$BLOCK_BUTTON" == 4 ]]; then
    change='+5'
elif [[ "$BLOCK_BUTTON" == 5 ]]; then
    change='-5'
fi

vol=$(~/.local/bin/scripts/quodlibet-volume "$change")
if [[ "$?" == 0 ]]; then
    if [[ "$BLOCK_BUTTON" == 2 ]]; then
        printf '\0play-pause\0/dev/null\0' > ~/.quodlibet/control
    fi

    printf "%s%%\n" "$vol"
fi
