#!/bin/bash
if [[ "$BLOCK_BUTTON" == 1 ]];
    then pamixer -i 5
elif [[ "$BLOCK_BUTTON" == 3 ]]; then
    pamixer -d 5
elif [[ "$BLOCK_BUTTON" == 2 ]]; then
    pamixer -t
fi

if $(pamixer --get-mute); then
    printf '\uf026  0%%\n\n#EEBF13'
else
    volume=$(pamixer --get-volume)
    printf '\uf028  %s%%' "$volume"
fi
