#!/bin/bash
if [[ "$BLOCK_BUTTON" == 4 ]]; then
    pamixer -i 5
elif [[ "$BLOCK_BUTTON" == 5 ]]; then
    pamixer -d 5
elif [[ "$BLOCK_BUTTON" == 2 ]]; then
    pamixer -t
fi

if $(pamixer --get-mute); then
    printf '\uf026  0\u2009%%\n\n#EEBF13'
else
    volume=$(pamixer --get-volume)
    printf '\uf028  %s\u2009%%' "$volume"
fi
